[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "dairy"
version = "0.0.1"
description = "Dairy Management System"
authors = [
    { name = "Sanskar Shukla", email = "sanskar19shukla@gmail.com" }
]
requires-python = ">=3.10"

dependencies = [
    # "frappe~=15.0.0" # Installed and managed by bench.
]

[tool.setuptools]
packages = ["dairy"]

[tool.setuptools.package-data]
dairy = ["**/*"]

[tool.bench.frappe-dependencies]
frappe = ">=15.0.0,<16.0.0"
